### ISSUE TITLE
Unexpected message causes crash

### ISSUE THREAD

**Issue by sgerbino** [koinos/koinos-block-store#43]
Using the MQ utility program, send a malformed message to the block store. It will result in a crash.
```
❯ ./programs/mq_client/Debug/koinos_mq_client --routing-key koinos_block --payload "{\"type\":\"koinos::rpc::chain::get_last_irreversible_block_request\",\"value\":{}}" | jq
Request timeout
```

This results in the following output to the block store:
```
❯ ./build/koinos-block-store
badger 2021/03/10 20:01:51 INFO: All 1 tables opened in 0s
badger 2021/03/10 20:01:51 INFO: Replaying file id: 0 at offset: 12959
badger 2021/03/10 20:01:51 INFO: Replay took: 4.378µs
badger 2021/03/10 20:01:51 DEBUG: Value log discard stats empty
2021/03/10 20:01:51 Connecting to AMQP server amqp://guest:guest@localhost:5672/
2021/03/10 20:01:51 Dialing AMQP server amqp://guest:guest@localhost:5672/
2021/03/10 20:01:51 Enter ConsumeRPCLoop
2021/03/10 20:01:51 Enter ConsumeBroadcastLoop
2021/03/10 20:01:51 Enter ConsumeBroadcastLoop
2021/03/10 20:01:51 Enter ConsumeRPCReturnLoop
2021/03/10 20:02:01 Error in RPC handler
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x13ee870]

goroutine 13 [running]:
github.com/koinos/koinos-mq-golang.(*connection).ConsumeRPCLoop(0xc0001aa050, 0xc00559e060, 0xc000030190, 0x14e9883, 0xc, 0xc0000c2900)
	/Users/sgerbino/go/pkg/mod/github.com/koinos/koinos-mq-golang@v0.0.0-20210205210801-8d044ae15573/koinosmq.go:572 +0x170
created by github.com/koinos/koinos-mq-golang.(*connection).Open
	/Users/sgerbino/go/pkg/mod/github.com/koinos/koinos-mq-golang@v0.0.0-20210205210801-8d044ae15573/koinosmq.go:384 +0x845
```

**Comment by sgerbino** [comment]
Resolved under #61.
